-- Create the table to store the official token
create table public.official_token (
  id bigint generated by default as identity primary key,
  mint text not null,
  name text,
  symbol text,
  image_uri text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for this table
alter publication supabase_realtime add table public.official_token;

-- Allow public read access (so everyone can see the token)
create policy "Public Read" on public.official_token
  for select using (true);

-- Allow public insert access (WARNING: In production, you should restrict this to your admin user or server-side only)
-- For this auto-hunting app to work from your client, we allow it for now.
create policy "Public Insert" on public.official_token
  for insert with check (true);

alter table public.official_token enable row level security;
